# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package files and TypeScript config
COPY package.json package-lock.json tsconfig.json ./

# Install all dependencies for build
RUN npm install

# Copy the TypeScript source files
COPY src ./src

# Compile the TypeScript code
RUN npm run build

# Make the script executable
RUN chmod +x dist/index.js

# Use a smaller Node.js runtime for the release build
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy compiled files from the build image
COPY --from=build /app/dist /app/dist

# Copy necessary package files
COPY --from=build /app/package.json /app/package-lock.json /app/

# Install only production dependencies
RUN npm install --omit=dev --ignore-scripts

# Set production environment
ENV NODE_ENV=production

# Set default browser configuration
ENV MCP_BROWSER_TYPE=chrome
ENV MCP_VIEWPORT_WIDTH=1280
ENV MCP_VIEWPORT_HEIGHT=800
ENV MCP_DEVICE_SCALE_FACTOR=1.25

# Set the user to non-root for security
USER node

# Run the server
ENTRYPOINT ["node", "dist/index.js"]